// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VolunteerInitiativesSystem.Data;

#nullable disable

namespace VolunteerInitiativesSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260223193839_AddCoordinator")]
    partial class AddCoordinator
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VolunteerInitiativesSystem.Models.Coordinator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Coordinators");
                });

            modelBuilder.Entity("VolunteerInitiativesSystem.Models.Initiative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoordinatorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CoordinatorId");

                    b.ToTable("Initiatives");
                });

            modelBuilder.Entity("VolunteerInitiativesSystem.Models.InitiativeParticipant", b =>
                {
                    b.Property<int>("InitiativeId")
                        .HasColumnType("int");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisteredOn")
                        .HasColumnType("datetime2");

                    b.HasKey("InitiativeId", "ParticipantId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("InitiativeParticipants");
                });

            modelBuilder.Entity("VolunteerInitiativesSystem.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("VolunteerInitiativesSystem.Models.Initiative", b =>
                {
                    b.HasOne("VolunteerInitiativesSystem.Models.Coordinator", "Coordinator")
                        .WithMany("Initiatives")
                        .HasForeignKey("CoordinatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coordinator");
                });

            modelBuilder.Entity("VolunteerInitiativesSystem.Models.InitiativeParticipant", b =>
                {
                    b.HasOne("VolunteerInitiativesSystem.Models.Initiative", "Initiative")
                        .WithMany("Registrations")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolunteerInitiativesSystem.Models.Participant", "Participant")
                        .WithMany("InitiativeParticipants")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("VolunteerInitiativesSystem.Models.Coordinator", b =>
                {
                    b.Navigation("Initiatives");
                });

            modelBuilder.Entity("VolunteerInitiativesSystem.Models.Initiative", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("VolunteerInitiativesSystem.Models.Participant", b =>
                {
                    b.Navigation("InitiativeParticipants");
                });
#pragma warning restore 612, 618
        }
    }
}
